# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5aded5d290d2aae8b23e2257b10281887383ec52bf9980835e7ab27d98d3d373da27ea6bd53da0ccd24a3f50b52bdf5460dc6decb8a76f7a995be88edbb48e96

test:
  secret_key_base: f5230a7ca66f6e5e2143a4da92de14b362c121ef2524e4a6e83bfec72df350d9e998bd9af7703ac168e0533009aeeae59c1989b3622819acca0b97b41cefcef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
